---
name: "[BETA] In-memory MariaDB"
version: 2.4.0.24-beta01
homeassistant: 2022.6.0
slug: mariadb-beta
description: "[BETA] An in-memory SQL database server"
url: https://github.com/lmagyar/homeassistant-addon-mariadb-inmemory
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
init: false
timeout: 20
tmpfs: true
privileged:
  - SYS_ADMIN
backup_pre: /command/s6-svc -wU -u /run/service/mariadb-lock/
backup_post: /command/s6-svc -wd -d /run/service/mariadb-lock/
services:
  - mysql:provide
ports:
  3306/tcp:
options:
  databases:
    - homeassistant
  logins:
    - username: homeassistant
      password:
  rights:
    - username: homeassistant
      database: homeassistant
schema:
  databases:
    - str
  logins:
    - username: str
      password: password
  rights:
    - username: str
      database: str
      privileges:
        - "list(ALTER|CREATE|CREATE ROUTINE|CREATE TEMPORARY TABLES|\
           CREATE VIEW|DELETE|DELETE HISTORY|DROP|EVENT|GRANT OPTION|INDEX|\
           INSERT|LOCK TABLES|SELECT|SHOW VIEW|TRIGGER|UPDATE)?"
image: lmagyar/{arch}-addon-mariadb-inmemory
